### ISSUE TITLE
Update URL Referenced to fairdatapipeline.org

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/FDP_hugo#28]
Url References should be updated to reflect the new domain (www.fairdatapipeline.org)

**Comment by bobturneruk** [comment]
Happy to have a look at this.

**Comment by bobturneruk** [comment]
What's the old domain to be replaced, please, @RyanJField ?

**Comment by RyanJField** [comment]
fairdatapipeline.github.io

**Comment by RyanJField** [comment]
> I'm probably being daft, but I can't see any references to this as a URL in itself. Only those referring to the repo of that name that hosts the built site.

You may be right, I assumed there would be some references to it as the repo itself is named fairdatapipeline.github.io, I assume all the links are relative then.

Sorry if you wasted your time on this.

**Comment by bobturneruk** [comment]
OK, I'm going to close. Please reopen if appropriate.
