### ISSUE TITLE
Outdated links in the R docs

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FDP_hugo#9]
@soniamitchell - this page - https://fairdatapipeline.github.io/docs/API/R/ - is a bit out of date in terms of links I think?

**Comment by soniamitchell** [comment]
It’s very out of date. We can remove the whole section if you want? It likely needs redone.

**Comment by richardreeve** [comment]
Whatever you think is best.

**Comment by soniamitchell** [comment]
I'll leave it for now as I'm not sure it's a priority. I'll try and update it with something a little more appropriate next week?

**Comment by richardreeve** [comment]
Sure - no rush. I just wasn't sure if you had noticed.

**Comment by soniamitchell** [comment]
done
